name: Make twrp-12.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Remove Useless Package
      run: |
        set -e
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt update
        sudo apt -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 1024
        swap-size-mb: 10240
        remove-dotnet: 'true'
        temp-reserve-mb: 1024
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare Environment
      run: |
        set -e
        export HOME=${GITHUB_WORKSPACE}
        cd ${GITHUB_WORKSPACE}
        sudo apt -y install git aria2
    - name: Init Repo
      run: |
        set -e
        sudo apt -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev git device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full android-sdk-libsparse-utils erofs-utils
        mkdir ${GITHUB_WORKSPACE}/workspace
        cd ${GITHUB_WORKSPACE}/workspace
        git config --global user.name "Hikaru's Action-Build-Bot"
        git config --global user.email "Android@teio.tk"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
    - name: Repo Sync
      run: |
        set -e
        cd ${GITHUB_WORKSPACE}/workspace
        repo sync -j$(nproc --all) -c --no-tags --no-clone-bundle --force-sync
        ls -al
    - name: Repopick Patches
      run: |
        set -e
        cd ${GITHUB_WORKSPACE}/workspace
        source build/envsetup.sh
        repopick 5405
        repopick 5540
        repopick 5493
        repopick 5639
        repopick 5653
    - name: Clone Device Tree
      run: |
        set -e
        cd ${GITHUB_WORKSPACE}/workspace
        git clone https://github.com/reigadegr/device_xiaomi_xaga-TWRP.git -b twrp-12.1 ./device/xiaomi/xaga
    - name: Building
      run: |
        set -e
        cd ${GITHUB_WORKSPACE}/workspace
        source build/envsetup.sh
        lunch twrp_xaga-eng
        mka vendorbootimage -j$(nproc --all)
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: xaga_twrp-12.1
        path: workspace/out/target/product/xaga/*.img
